language: python

install:
  - pip install mkdocs

script: 
  - mkdocs --version
  - mkdocs build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: site/  # Directory to push to GitHub Pages, defaults to current directory.
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: feature/doc