site_name: Pharo Launcher documentation
nav:
    - index.md
    - installation.md
    - create-images.md
    - commands.md 
    - launch-configurations.md 
    - templates.md
    - manage-vms.md     
    - settings.md
                         
theme:
    name: readthedocs